// Code generated by oapi-codegen; DO NOT EDIT.

package supporttickets

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type CreateTicketJSONRequestBody = models.SupportV1CreateTicketRequest

type AddTicketMessageJSONRequestBody = any

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// ListCategories makes a GET request to /support/v1/categories
	ListCategories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListTopics2 makes a GET request to /support/v1/categories/{category_id}/topics
	ListTopics2(ctx context.Context, categoryId string, params *ListTopics2Params, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListTickets makes a GET request to /support/v1/tickets
	ListTickets(ctx context.Context, params *ListTicketsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateTicketWithBody makes a POST request to /support/v1/tickets
	CreateTicketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateTicket(ctx context.Context, body CreateTicketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetTicket makes a GET request to /support/v1/tickets/{ticket_id}
	GetTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CloseTicket makes a POST request to /support/v1/tickets/{ticket_id}/close
	CloseTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// AddTicketMessageWithBody makes a POST request to /support/v1/tickets/{ticket_id}/messages
	AddTicketMessageWithBody(ctx context.Context, ticketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	AddTicketMessage(ctx context.Context, ticketId string, body AddTicketMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListTopics makes a GET request to /support/v1/topics
	ListTopics(ctx context.Context, params *ListTopicsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListTopics2Params defines parameters for ListTopics2.
type ListTopics2Params struct {
	// query (optional)
	Query *string `form:"query" json:"query"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	// pagination.limit (optional)
	PaginationLimit *int32 `form:"pagination.limit" json:"pagination.limit"`
	// pagination.offset (optional)
	PaginationOffset *int32 `form:"pagination.offset" json:"pagination.offset"`
	// status (optional)
	Status *SupportV1TicketStatus `form:"status" json:"status"`
}

// ListTopicsParams defines parameters for ListTopics.
type ListTopicsParams struct {
	// category_id (optional)
	CategoryId *string `form:"category_id" json:"category_id"`
	// query (optional)
	Query *string `form:"query" json:"query"`
}

// ListCategories makes a GET request to /support/v1/categories
// ListCategories
func (c *Client) ListCategories(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCategoriesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListTopics2 makes a GET request to /support/v1/categories/{category_id}/topics
// ListTopics
func (c *Client) ListTopics2(ctx context.Context, categoryId string, params *ListTopics2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTopics2Request(c.Server, categoryId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListTickets makes a GET request to /support/v1/tickets
// ListTickets
func (c *Client) ListTickets(ctx context.Context, params *ListTicketsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTicketsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTicketWithBody makes a POST request to /support/v1/tickets
// CreateTicket
func (c *Client) CreateTicketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTicketRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateTicket makes a POST request to /support/v1/tickets with application/json body
func (c *Client) CreateTicket(ctx context.Context, body CreateTicketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTicketRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetTicket makes a GET request to /support/v1/tickets/{ticket_id}
// GetTicket
func (c *Client) GetTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTicketRequest(c.Server, ticketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CloseTicket makes a POST request to /support/v1/tickets/{ticket_id}/close
// CloseTicket
func (c *Client) CloseTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCloseTicketRequest(c.Server, ticketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AddTicketMessageWithBody makes a POST request to /support/v1/tickets/{ticket_id}/messages
// AddTicketMessage
func (c *Client) AddTicketMessageWithBody(ctx context.Context, ticketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddTicketMessageRequestWithBody(c.Server, ticketId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AddTicketMessage makes a POST request to /support/v1/tickets/{ticket_id}/messages with application/json body
func (c *Client) AddTicketMessage(ctx context.Context, ticketId string, body AddTicketMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddTicketMessageRequest(c.Server, ticketId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListTopics makes a GET request to /support/v1/topics
// ListTopics
func (c *Client) ListTopics(ctx context.Context, params *ListTopicsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTopicsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListCategoriesRequest creates a GET request for /support/v1/categories
func NewListCategoriesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/categories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTopics2Request creates a GET request for /support/v1/categories/{category_id}/topics
func NewListTopics2Request(server string, categoryId string, params *ListTopics2Params) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("category_id", categoryId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/categories/%s/topics", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Query != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("query", *params.Query, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListTicketsRequest creates a GET request for /support/v1/tickets
func NewListTicketsRequest(server string, params *ListTicketsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/tickets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.PaginationLimit != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("pagination.limit", *params.PaginationLimit, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.PaginationOffset != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("pagination.offset", *params.PaginationOffset, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Status != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("status", *params.Status, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTicketRequest creates a POST request for /support/v1/tickets with application/json body
func NewCreateTicketRequest(server string, body CreateTicketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTicketRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTicketRequestWithBody creates a POST request for /support/v1/tickets with any body
func NewCreateTicketRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/tickets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetTicketRequest creates a GET request for /support/v1/tickets/{ticket_id}
func NewGetTicketRequest(server string, ticketId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("ticket_id", ticketId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/tickets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCloseTicketRequest creates a POST request for /support/v1/tickets/{ticket_id}/close
func NewCloseTicketRequest(server string, ticketId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("ticket_id", ticketId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/tickets/%s/close", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddTicketMessageRequest creates a POST request for /support/v1/tickets/{ticket_id}/messages with application/json body
func NewAddTicketMessageRequest(server string, ticketId string, body AddTicketMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddTicketMessageRequestWithBody(server, ticketId, "application/json", bodyReader)
}

// NewAddTicketMessageRequestWithBody creates a POST request for /support/v1/tickets/{ticket_id}/messages with any body
func NewAddTicketMessageRequestWithBody(server string, ticketId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("ticket_id", ticketId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/tickets/%s/messages", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListTopicsRequest creates a GET request for /support/v1/topics
func NewListTopicsRequest(server string, params *ListTopicsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/support/v1/topics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.CategoryId != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("category_id", *params.CategoryId, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Query != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("query", *params.Query, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// ListCategories makes a GET request to /support/v1/categories and returns the parsed response.
// ListCategories
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListCategories(ctx context.Context, reqEditors ...RequestEditorFn) (models.SupportV1ListCategoriesResponse, error) {
	var result models.SupportV1ListCategoriesResponse
	resp, err := c.Client.ListCategories(ctx, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListTopics2 makes a GET request to /support/v1/categories/{category_id}/topics and returns the parsed response.
// ListTopics
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListTopics2(ctx context.Context, categoryId string, params *ListTopics2Params, reqEditors ...RequestEditorFn) (models.SupportV1ListTopicsResponse, error) {
	var result models.SupportV1ListTopicsResponse
	resp, err := c.Client.ListTopics2(ctx, categoryId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListTickets makes a GET request to /support/v1/tickets and returns the parsed response.
// ListTickets
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListTickets(ctx context.Context, params *ListTicketsParams, reqEditors ...RequestEditorFn) (models.SupportV1ListTicketsResponse, error) {
	var result models.SupportV1ListTicketsResponse
	resp, err := c.Client.ListTickets(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CreateTicket makes a POST request to /support/v1/tickets and returns the parsed response.
// CreateTicket
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CreateTicket(ctx context.Context, body CreateTicketJSONRequestBody, reqEditors ...RequestEditorFn) (models.SupportV1CreateTicketResponse, error) {
	var result models.SupportV1CreateTicketResponse
	resp, err := c.Client.CreateTicket(ctx, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetTicket makes a GET request to /support/v1/tickets/{ticket_id} and returns the parsed response.
// GetTicket
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (models.SupportV1GetTicketResponse, error) {
	var result models.SupportV1GetTicketResponse
	resp, err := c.Client.GetTicket(ctx, ticketId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// CloseTicket makes a POST request to /support/v1/tickets/{ticket_id}/close and returns the parsed response.
// CloseTicket
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) CloseTicket(ctx context.Context, ticketId string, reqEditors ...RequestEditorFn) (models.SupportV1CloseTicketResponse, error) {
	var result models.SupportV1CloseTicketResponse
	resp, err := c.Client.CloseTicket(ctx, ticketId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// AddTicketMessage makes a POST request to /support/v1/tickets/{ticket_id}/messages and returns the parsed response.
// AddTicketMessage
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) AddTicketMessage(ctx context.Context, ticketId string, body AddTicketMessageJSONRequestBody, reqEditors ...RequestEditorFn) (models.SupportV1AddTicketMessageResponse, error) {
	var result models.SupportV1AddTicketMessageResponse
	resp, err := c.Client.AddTicketMessage(ctx, ticketId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// ListTopics makes a GET request to /support/v1/topics and returns the parsed response.
// ListTopics
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) ListTopics(ctx context.Context, params *ListTopicsParams, reqEditors ...RequestEditorFn) (models.SupportV1ListTopicsResponse, error) {
	var result models.SupportV1ListTopicsResponse
	resp, err := c.Client.ListTopics(ctx, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
