// Code generated by oapi-codegen; DO NOT EDIT.

package chapters

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/rixlhq/rixl-go/sdk/models"
	oapiCodegenParamsPkg "github.com/rixlhq/rixl-go/sdk/runtime/params"
)

type UpdateVideoChaptersJSONRequestBody = any

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// UpdateVideoChapters2 makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
	UpdateVideoChapters2(ctx context.Context, projectId string, videoId string, params *UpdateVideoChapters2Params, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetVideoChapters makes a GET request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
	GetVideoChapters(ctx context.Context, projectId string, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// UpdateVideoChaptersWithBody makes a PUT request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
	UpdateVideoChaptersWithBody(ctx context.Context, projectId string, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	UpdateVideoChapters(ctx context.Context, projectId string, videoId string, body UpdateVideoChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteVideoChapter makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters/{start_time_sec}
	DeleteVideoChapter(ctx context.Context, projectId string, videoId string, startTimeSec int64, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// UpdateVideoChapters2Params defines parameters for UpdateVideoChapters2.
type UpdateVideoChapters2Params struct {
	// chapters.title (optional)
	ChaptersTitle *string `form:"chapters.title" json:"chapters.title"`
	// chapters.start_time_sec (optional)
	ChaptersStartTimeSec *float64 `form:"chapters.start_time_sec" json:"chapters.start_time_sec"`
}

// UpdateVideoChapters2 makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
// UpdateVideoChapters
func (c *Client) UpdateVideoChapters2(ctx context.Context, projectId string, videoId string, params *UpdateVideoChapters2Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVideoChapters2Request(c.Server, projectId, videoId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVideoChapters makes a GET request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
// GetVideoChapters
func (c *Client) GetVideoChapters(ctx context.Context, projectId string, videoId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVideoChaptersRequest(c.Server, projectId, videoId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateVideoChaptersWithBody makes a PUT request to /media/v1/projects/{project_id}/videos/{video_id}/chapters
// UpdateVideoChapters
func (c *Client) UpdateVideoChaptersWithBody(ctx context.Context, projectId string, videoId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVideoChaptersRequestWithBody(c.Server, projectId, videoId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateVideoChapters makes a PUT request to /media/v1/projects/{project_id}/videos/{video_id}/chapters with application/json body
func (c *Client) UpdateVideoChapters(ctx context.Context, projectId string, videoId string, body UpdateVideoChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateVideoChaptersRequest(c.Server, projectId, videoId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteVideoChapter makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters/{start_time_sec}
// DeleteVideoChapter
func (c *Client) DeleteVideoChapter(ctx context.Context, projectId string, videoId string, startTimeSec int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteVideoChapterRequest(c.Server, projectId, videoId, startTimeSec)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUpdateVideoChapters2Request creates a DELETE request for /media/v1/projects/{project_id}/videos/{video_id}/chapters
func NewUpdateVideoChapters2Request(server string, projectId string, videoId string, params *UpdateVideoChapters2Params) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("project_id", projectId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/media/v1/projects/%s/videos/%s/chapters", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.ChaptersTitle != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("chapters.title", *params.ChaptersTitle, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.ChaptersStartTimeSec != nil {
			if queryFrag, err := oapiCodegenParamsPkg.StyleParameter("chapters.start_time_sec", *params.ChaptersStartTimeSec, oapiCodegenParamsPkg.ParameterOptions{Style: "form", ParamLocation: oapiCodegenParamsPkg.ParamLocationQuery, Explode: true, Required: false, Type: "number", Format: "double", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVideoChaptersRequest creates a GET request for /media/v1/projects/{project_id}/videos/{video_id}/chapters
func NewGetVideoChaptersRequest(server string, projectId string, videoId string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("project_id", projectId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/media/v1/projects/%s/videos/%s/chapters", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateVideoChaptersRequest creates a PUT request for /media/v1/projects/{project_id}/videos/{video_id}/chapters with application/json body
func NewUpdateVideoChaptersRequest(server string, projectId string, videoId string, body UpdateVideoChaptersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateVideoChaptersRequestWithBody(server, projectId, videoId, "application/json", bodyReader)
}

// NewUpdateVideoChaptersRequestWithBody creates a PUT request for /media/v1/projects/{project_id}/videos/{video_id}/chapters with any body
func NewUpdateVideoChaptersRequestWithBody(server string, projectId string, videoId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("project_id", projectId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/media/v1/projects/%s/videos/%s/chapters", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteVideoChapterRequest creates a DELETE request for /media/v1/projects/{project_id}/videos/{video_id}/chapters/{start_time_sec}
func NewDeleteVideoChapterRequest(server string, projectId string, videoId string, startTimeSec int64) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = oapiCodegenParamsPkg.StyleParameter("project_id", projectId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = oapiCodegenParamsPkg.StyleParameter("video_id", videoId, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam2 string
	pathParam2, err = oapiCodegenParamsPkg.StyleParameter("start_time_sec", startTimeSec, oapiCodegenParamsPkg.ParameterOptions{Style: "simple", ParamLocation: oapiCodegenParamsPkg.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/media/v1/projects/%s/videos/%s/chapters/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientHttpError represents an HTTP error response.
// The type parameter E is the type of the parsed error body.
type ClientHttpError[E any] struct {
	StatusCode int
	Body       E
	RawBody    []byte
}

func (e *ClientHttpError[E]) Error() string {
	return fmt.Sprintf("HTTP %d", e.StatusCode)
}

// SimpleClient wraps Client with typed responses for operations that have
// unambiguous response types. Methods return the success type directly,
// and HTTP errors are returned as *ClientHttpError[E] where E is the error type.
type SimpleClient struct {
	*Client
}

// NewSimpleClient creates a new SimpleClient which wraps a Client.
func NewSimpleClient(server string, opts ...ClientOption) (*SimpleClient, error) {
	inner, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &SimpleClient{Client: inner}, nil
}

// UpdateVideoChapters2 makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters and returns the parsed response.
// UpdateVideoChapters
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) UpdateVideoChapters2(ctx context.Context, projectId string, videoId string, params *UpdateVideoChapters2Params, reqEditors ...RequestEditorFn) (models.VideosV1VideoChapters, error) {
	var result models.VideosV1VideoChapters
	resp, err := c.Client.UpdateVideoChapters2(ctx, projectId, videoId, params, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// GetVideoChapters makes a GET request to /media/v1/projects/{project_id}/videos/{video_id}/chapters and returns the parsed response.
// GetVideoChapters
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) GetVideoChapters(ctx context.Context, projectId string, videoId string, reqEditors ...RequestEditorFn) (models.VideosV1VideoChapters, error) {
	var result models.VideosV1VideoChapters
	resp, err := c.Client.GetVideoChapters(ctx, projectId, videoId, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// UpdateVideoChapters makes a PUT request to /media/v1/projects/{project_id}/videos/{video_id}/chapters and returns the parsed response.
// UpdateVideoChapters
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) UpdateVideoChapters(ctx context.Context, projectId string, videoId string, body UpdateVideoChaptersJSONRequestBody, reqEditors ...RequestEditorFn) (models.VideosV1VideoChapters, error) {
	var result models.VideosV1VideoChapters
	resp, err := c.Client.UpdateVideoChapters(ctx, projectId, videoId, body, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}

// DeleteVideoChapter makes a DELETE request to /media/v1/projects/{project_id}/videos/{video_id}/chapters/{start_time_sec} and returns the parsed response.
// DeleteVideoChapter
// On success, returns the response body. On HTTP error, returns *ClientHttpError[struct{}].
func (c *SimpleClient) DeleteVideoChapter(ctx context.Context, projectId string, videoId string, startTimeSec int64, reqEditors ...RequestEditorFn) (models.VideosV1VideoChapters, error) {
	var result models.VideosV1VideoChapters
	resp, err := c.Client.DeleteVideoChapter(ctx, projectId, videoId, startTimeSec, reqEditors...)
	if err != nil {
		return result, err
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return result, err
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if err := json.Unmarshal(rawBody, &result); err != nil {
			return result, err
		}
		return result, nil
	}

	// No typed error response defined
	return result, &ClientHttpError[struct{}]{
		StatusCode: resp.StatusCode,
		RawBody:    rawBody,
	}
}
